### ISSUE TITLE
Not really an issue, but....

### ISSUE THREAD

**Issue by JustinGlen75** [gabenasci/yt-remove-watched-videos#3]
I wanted to ask if there's a way to alter the code - or a separate code -  that would just completely wipe out - purge - the Watch Later list completely, including videos that have not been watched yet? I think that would be awesome! Why YT doesn't have a simple button to do just that is beyond me. Thanks for the hard work!

**Comment by gabenasci** [comment]
Thanks for the feedback Justin. I'll update it soon with an option to remove all videos from the playlist, should be a simple tweak.

**Comment by gabenasci** [comment]
Added an option to remove all videos from WL

[fd0c3d7eac9d6e76d332b1d584fcc56311edb853](https://github.com/gabenasci/yt-remove-watched-videos/commit/fd0c3d7eac9d6e76d332b1d584fcc56311edb853)
